### ISSUE TITLE
Failed/Partial Read will not close the file

### ISSUE THREAD

**Issue by XDelta** [dfgHiatus/ResoniteUnityPackagesImporter#13]
Consider 'using' statements for file-stream reads as they will close open file handles as soon as they are done and out of scope. This also will ensure that the file is closed even if an exception occurs. 

` using (var stream = System.IO.File.OpenRead(filepath)) {`
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement

**Comment by dfgHiatus** [comment]
[UnityPackageExtractor.txt](https://github.com/dfgHiatus/NeosUnityPackagesImporter/files/9211997/UnityPackageExtractor.txt)

Interestingly, this yields some invalid paths on import. This will require further investigation.

**Comment by dfgHiatus** [comment]
Logic for this was added v1.3.0
