### ISSUE TITLE
Add more info to description

### ISSUE THREAD

**Issue by BlueCyro** [dfgHiatus/ResoniteUnityPackagesImporter#9]
It may be prudent to alter the README to include more information about what this mod actually does. I feel as though people may - as I have - erroneously assumed that this would actually bring in objects from the scene with the proper hierarchies rather than just facilitate the import of files via file dialogs.

**Comment by dfgHiatus** [comment]
Sure thing, I'll add some substance

**Comment by dfgHiatus** [comment]
Added some FAQs, feel free to reopen with suggestions
